import {projects,routes} from './content.js';
const nav=`<canvas id="ascii-world" class="ascii-backdrop" aria-hidden="true"></canvas><header class="site-header"><a class="brand" href="/home" data-link>SHAYAN MONDAL</a><nav aria-label="Primary"><a href="/home" data-link>Home</a><a href="/work" data-link>Work</a><a href="/about" data-link>About</a><a href="/contact" data-link>Contact</a></nav><a class="github" href="https://github.com/ShayanBytes" target="_blank" rel="noreferrer">GitHub ↗</a></header>`;
const enter=()=>`<main class="enter"><canvas id="ascii-world" aria-hidden="true"></canvas><div class="enter__shade" aria-hidden="true"></div><div class="enter__top"><span>SHAYAN MONDAL</span><span>DEVELOPER / INDIA</span></div><section class="enter__content"><p class="eyebrow">A living index of code, systems, and experiments</p><h1>Enter my<br><em>world.</em></h1><p class="enter__intro">I build useful software and explore what happens when engineering meets curiosity.</p><a class="enter-button" href="/home" data-link>Explore portfolio</a></section><p class="enter__hint">Move your cursor through the organism</p></main>`;
const home=()=>`${nav}<main class="standard home"><section class="home-hero"><p class="eyebrow">Developer · Systems thinker · Builder</p><h1>I turn difficult<br>problems into<br><em>working software.</em></h1><p>From distributed databases to full-stack products and Python tools, I learn by building systems from the inside out.</p><div class="actions"><a class="button" href="/work" data-link>View selected work</a><a class="text-link" href="https://github.com/ShayanBytes" target="_blank">Browse GitHub ↗</a></div></section><footer class="page-footer"><span>Bongaon, West Bengal</span><span>Available for thoughtful collaborations</span></footer></main>`;
const work=()=>`${nav}<main class="standard"><header class="page-title"><p class="eyebrow">Selected repositories</p><h1>Real work.<br><em>No mockups.</em></h1><p>Projects drawn directly from my GitHub—systems, products, and tools that represent how I think and build.</p></header><section class="repo-list">${projects.map((p,i)=>`<a class="repo" href="${p.href}" target="_blank" rel="noreferrer"><span class="repo__number">0${i+1}</span><div><p>${p.type}</p><h2>${p.name}</h2><p>${p.description}</p></div><span class="repo__open">Open repository ↗</span></a>`).join('')}</section></main>`;
const about=()=>`${nav}<main class="standard"><header class="page-title"><p class="eyebrow">About</p><h1>Curious enough<br>to go <em>deeper.</em></h1></header><section class="about-copy"><p>I’m Shayan Mondal, a computer science student and developer from Bongaon, West Bengal.</p><p>My repositories move across Java, TypeScript, Python, JavaScript, databases, full-stack products, and problem solving. That range is intentional: I care less about staying inside one label and more about understanding how software works as a whole.</p><dl><div><dt>Current focus</dt><dd>Distributed systems, product engineering, developer tools</dd></div><div><dt>Languages seen in my work</dt><dd>Java, TypeScript, Python, JavaScript, HTML/CSS</dd></div><div><dt>Approach</dt><dd>Learn the fundamentals. Build the real thing. Document the process.</dd></div></dl></section></main>`;
const contact=()=>`${nav}<main class="standard contact"><p class="eyebrow">Contact</p><h1>Let’s build<br>something <em>useful.</em></h1><a class="email" href="mailto:sayanroman9090@gmail.com">sayanroman9090@gmail.com</a><div class="contact-links"><a href="https://github.com/ShayanBytes" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/shayan-mondal-1338bb340/" target="_blank">LinkedIn ↗</a></div></main>`;
const templates={enter,home,work,about,contact};
export function resolve(){const r=location.pathname.split('/').filter(Boolean).pop()||'enter';return routes.includes(r)?r:'enter'}
export function render(route){return templates[route]();}
