import {projects,routes} from './content.js';
const RAW='https://raw.githubusercontent.com/ShayanBytes/Portfolio/main/';
const icons=`<svg viewBox="0 0 80 80"><circle cx="40" cy="40" r="36"/><path d="M25 40h29m-9-10 10 10-10 10"/></svg>`;
const home=()=>`<main class="page home" data-world="home"><section class="hero"><p class="kicker split">CREATIVE DEVELOPER · PRODUCT THINKER · WORLD BUILDER</p><h1><span class="serif split">Ideas should not</span><span class="sans split">sit <em>still.</em></span></h1><p class="intro reveal">I’m Shayan Mondal. I build digital experiences where engineering becomes atmosphere and interaction becomes memory.</p><a data-link href="/work" class="orb-link magnet"><span>ENTER THE WORLDS</span>${icons}</a></section><section class="home-statement"><p data-kinetic>Code is material.<br>Motion is language.<br>Curiosity is the engine.</p></section><section class="portal"><a data-link href="/about"><span>Next environment</span><strong>IDENTITY</strong>${icons}</a></section></main>`;
const work=()=>`<main class="page work" data-world="work"><header class="page-head"><p>02 / MEMORY WORLDS</p><h1 class="split">Selected<br><i>realities.</i></h1><span>Drag / Scroll / Explore</span></header><div class="world-stack">${projects.map((p,i)=>`<article class="world-card reveal" style="--i:${i}"><a href="${p.image}" target="_blank"><figure><img src="${RAW}${p.image.slice(1)}" alt="${p.title} interface study" loading="lazy"><div class="scan"></div></figure><div class="world-meta"><small>${p.id} · ${p.type} · ${p.year}</small><h2>${p.title}</h2><p>${p.note}</p><span>EXPLORE ARTIFACT ↗</span></div></a></article>`).join('')}</div><section class="portal"><a data-link href="/laboratory"><span>Beyond client space</span><strong>LABORATORY</strong>${icons}</a></section></main>`;
const about=()=>`<main class="page about" data-world="about"><header class="page-head"><p>03 / IDENTITY</p><h1 class="split">Human,<br><i>in progress.</i></h1></header><section class="portrait-zone"><figure class="portrait"><img src="${RAW}background-replacer-result.png" alt="Portrait of Shayan Mondal"><canvas id="ascii" aria-hidden="true"></canvas><figcaption>Move across the image to resolve the signal</figcaption></figure><div class="bio"><p class="lead reveal">A computer science student from Bongaon, India—working where systems, aesthetics, and emerging technology meet.</p><p class="reveal">I’m interested in the invisible decisions that make an experience feel natural: pacing, feedback, hierarchy, and the exact moment complexity disappears.</p><dl class="reveal"><div><dt>DISCIPLINES</dt><dd>Full-stack / Product / AI-ML / Direction</dd></div><div><dt>STATUS</dt><dd>Available for select collaborations</dd></div><div><dt>PHILOSOPHY</dt><dd>Question the obvious. Prototype the impossible.</dd></div></dl></div></section><section class="portal"><a data-link href="/archive"><span>Trace the path</span><strong>ARCHIVE</strong>${icons}</a></section></main>`;
const laboratory=()=>`<main class="page laboratory" data-world="laboratory"><header class="page-head"><p>04 / LABORATORY</p><h1 class="split">Unfinished<br><i>on purpose.</i></h1><span>Live GPU experiments</span></header><section class="experiments"><button class="experiment active" data-mode="flow"><small>EXP / 001</small><strong>FLOW FIELD</strong><span>Cursor-disturbed particle weather</span></button><button class="experiment" data-mode="gravity"><small>EXP / 002</small><strong>GRAVITY WELL</strong><span>Mass, orbit, and digital tension</span></button><button class="experiment" data-mode="signal"><small>EXP / 003</small><strong>LOST SIGNAL</strong><span>Image memory through interference</span></button></section><p class="lab-note">The laboratory is not a gallery of finished things. It is evidence of curiosity—small systems built to discover what an interface could become.</p><section class="portal"><a data-link href="/contact"><span>Make something new</span><strong>SEND A SIGNAL</strong>${icons}</a></section></main>`;
const archive=()=>`<main class="page archive" data-world="archive"><header class="page-head"><p>05 / TRAJECTORY</p><h1 class="split">An infinite<br><i>corridor.</i></h1></header><section class="corridor"><article><span>NOW</span><h2>Shayan Ventures</h2><p>Founder / CEO</p><small>BUILDING PRODUCTS, TEAMS, AND CONVICTION.</small></article><article><span>02</span><h2>ShayanBytes</h2><p>AI/ML Product Manager</p><small>CONNECTING EMERGING TECHNOLOGY TO HUMAN NEEDS.</small></article><article><span>01</span><h2>Adobe</h2><p>Web Developer</p><small>DEVELOPING CRAFT ACROSS INTERFACES AND SYSTEMS.</small></article></section><section class="portal"><a data-link href="/home"><span>Return to origin</span><strong>HOME</strong>${icons}</a></section></main>`;
const contact=()=>`<main class="page contact" data-world="contact"><section class="signal"><p>06 / OPEN CHANNEL</p><h1 class="split">Transmit<br><i>an idea.</i></h1><a href="mailto:sayanroman9090@gmail.com" class="signal-link magnet">SAYANROMAN9090@GMAIL.COM <span>↗</span></a><div class="coordinates"><span>BONGAON / INDIA</span><span>LOCAL TIME <b data-time></b></span><span>RESPONSE / 24—48H</span></div></section><footer><span>© ${new Date().getFullYear()} SHAYAN MONDAL</span><div><a href="https://github.com/ShayanBytes" target="_blank">GITHUB ↗</a><a href="https://www.linkedin.com/in/shayan-mondal-1338bb340/" target="_blank">LINKEDIN ↗</a><a href="https://x.com/fox_xrr" target="_blank">X ↗</a></div></footer></main>`;
const templates={home,work,about,laboratory,archive,contact};
export function resolve(){const r=location.pathname.split('/').filter(Boolean).pop()||'home';return routes.includes(r)?r:'home'}
export function render(route){return templates[route]();}
