import * as THREE from 'three';
const vertex=`uniform float uTime;uniform float uScroll;uniform vec2 uMouse;varying float vWave;void main(){vec3 p=position;float d=length(p.xy-uMouse*2.);float w=sin(p.x*1.4+uTime)*.22+cos(p.y*1.7-uTime*.7)*.18;p.z+=w+uScroll*.5+exp(-d)*.35;vWave=w;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);gl_PointSize=2.2;}`;
const fragment=`uniform vec3 uA;uniform vec3 uB;varying float vWave;void main(){float d=length(gl_PointCoord-.5);if(d>.48)discard;vec3 c=mix(uA,uB,smoothstep(-.4,.4,vWave));gl_FragColor=vec4(c,1.-d*1.5);}`;
const palettes={home:[0xd9ff43,0x5454ff],work:[0xff593d,0xffd36a],about:[0xd7d0c2,0x456dff],laboratory:[0x83ffcf,0x943dff],archive:[0xe5e1d7,0x7458ff],contact:[0xff402f,0xffd729]};
export class World{
 constructor(canvas){this.canvas=canvas;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,100);this.camera.position.z=5.5;this.renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:devicePixelRatio<2,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.clock=new THREE.Clock();this.mouse=new THREE.Vector2();this.scroll=0;this.targetScroll=0;this.build();this.resize();addEventListener('resize',()=>this.resize());addEventListener('pointermove',e=>this.mouse.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight*2-1)),{passive:true});this.loop();}
 build(){const n=innerWidth<700?3200:9000;const pos=new Float32Array(n*3);for(let i=0;i<n;i++){const r=2.8*Math.sqrt(Math.random());const a=Math.random()*Math.PI*2;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=Math.sin(a)*r;pos[i*3+2]=(Math.random()-.5)*2;}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));this.mat=new THREE.ShaderMaterial({vertexShader:vertex,fragmentShader:fragment,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uScroll:{value:0},uMouse:{value:new THREE.Vector2()},uA:{value:new THREE.Color(0xd9ff43)},uB:{value:new THREE.Color(0x5454ff)}}});this.points=new THREE.Points(geo,this.mat);this.scene.add(this.points);const knot=new THREE.Mesh(new THREE.TorusKnotGeometry(1.25,.28,180,18),new THREE.MeshBasicMaterial({color:0xffffff,wireframe:true,transparent:true,opacity:.13}));this.knot=knot;this.scene.add(knot);}
 route(name){const p=palettes[name]||palettes.home;this.mat.uniforms.uA.value.setHex(p[0]);this.mat.uniforms.uB.value.setHex(p[1]);this.points.rotation.set(Math.random()*.5,Math.random()*.5,0);this.knot.visible=name==='laboratory'||name==='archive';this.canvas.dataset.route=name;}
 mode(mode){this.knot.visible=mode!=='flow';this.knot.geometry.dispose();this.knot.geometry=mode==='gravity'?new THREE.TorusKnotGeometry(1.1,.36,220,24,3,5):new THREE.IcosahedronGeometry(1.5,3);}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight,false);}
 loop(){requestAnimationFrame(()=>this.loop());if(document.hidden)return;const t=this.clock.getElapsedTime();this.targetScroll=scrollY/(Math.max(1,document.body.scrollHeight-innerHeight));this.scroll+=(this.targetScroll-this.scroll)*.04;this.mat.uniforms.uTime.value=this.reduced?0:t*.45;this.mat.uniforms.uScroll.value=this.scroll;this.mat.uniforms.uMouse.value.lerp(this.mouse,.05);this.points.rotation.z=t*.015+this.scroll*.8;this.knot.rotation.x=t*.08+this.scroll;this.knot.rotation.y=t*.12;this.camera.position.y=-this.scroll*.8;this.renderer.render(this.scene,this.camera);}
}
